create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  booking_time time not null,
  category text not null check (category in ('peluqueria', 'depilacion', 'manicura', 'pedicura')),
  service text not null,
  created_at timestamptz not null default now(),
  unique (booking_date, booking_time, category)
);

alter table public.bookings enable row level security;

drop policy if exists "Public can read bookings" on public.bookings;
create policy "Public can read bookings"
  on public.bookings for select
  to anon
  using (true);

drop policy if exists "Public can create bookings" on public.bookings;
create policy "Public can create bookings"
  on public.bookings for insert
  to anon
  with check (true);
